# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/xenial64"

    config.vm.network "private_network", ip: "192.168.10.50"

    config.vm.synced_folder ".", "/opt/dev/th2c"

    config.vm.provision "shell", path: "../provision.sh"
end
